name: Autolint with black

on:
  push:
    branches:
      - main

jobs:

  lint-autofix:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Needed for manual push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Auto-fix with black
        run: black --line-length 120 .

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-fix Python lint issues"
            git rebase origin/${{ github.head_ref }}
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:refs/heads/${{ github.head_ref }}
          fi
        env:
          # Required if using a token for push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}